# Generated by Django 4.1.2 on 2023-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='material',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
