# Generated by Django 4.1.2 on 2023-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cartitem_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Success',
            field=models.BooleanField(default=False),
        ),
    ]
